# Generated by Django 4.1.7 on 2023-03-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_invitation_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='not_coming',
            field=models.BooleanField(default=False),
        ),
    ]
