# Generated by Django 4.2.3 on 2023-07-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallery_photo_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
    ]
